version: 1
trusted_only: true

passes:
  # Static analysis (free, always runs)
  - name: static
    agents: [semgrep]
    enabled: true

  # Local LLM review (free, requires Ollama sidecar)
  - name: local-ai
    agents: [local_llm]
    enabled: true

  # Cloud AI review (uses Anthropic Claude)
  - name: cloud-ai
    agents: [opencode]
    enabled: true

limits:
  max_files: 50
  max_diff_lines: 2000

reporting:
  github:
    mode: checks_and_comments
    max_inline_comments: 20

gating:
  enabled: false
  fail_on_severity: error
