version: 1
trusted_only: true

passes:
  # Static analysis (free, always runs)
  - name: static
    agents: [semgrep]
    enabled: true

  # Local LLM review (free, requires Ollama sidecar)
  - name: local-ai
    agents: [local_llm]
    enabled: true

  # Cloud AI review (uses Anthropic Claude)
  - name: cloud-ai
    agents: [opencode]
    enabled: true

# Model configuration - use Anthropic Claude
models:
  default: claude-sonnet-4-20250514

# Limits sized for PR #50: 111 files, 81,741 diff lines
limits:
  max_files: 150
  max_diff_lines: 100000
  max_tokens_per_pr: 700000
  max_usd_per_pr: 50.00
  monthly_budget_usd: 500

reporting:
  github:
    mode: checks_and_comments
    max_inline_comments: 50

gating:
  enabled: false
  fail_on_severity: error
