# Extension Verification Test Pipeline
# Purpose: Test the ADO extension task (not just CLI)
# Uses: ExtractPullRequests@1 task from the installed extension

trigger: none  # Manual only

pool:
  name: 'Default'

variables:
  - group: ado-insights-secrets  # Contains PAT_SECRET
  - name: ARTIFACT_NAME
    value: 'ado-insights-db-ext-test'  # Isolated namespace for extension testing

stages:
  - stage: Extract
    displayName: 'Extract via Extension'
    jobs:
      - job: ExtractPRs
        displayName: 'Run Extension Task'
        steps:
          # Download previous database (if exists)
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Previous Database (Golden)'
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: '$(Build.DefinitionId)'
              buildVersionToDownload: 'latest'
              allowFailedBuilds: false
              artifactName: '$(ARTIFACT_NAME)'
              targetPath: '$(Pipeline.Workspace)/data'
            continueOnError: true

          # Log artifact status
          - script: |
              if [ -f "$(Pipeline.Workspace)/data/ado-insights.sqlite" ]; then
                echo "##[section]Found existing database (Run 2+)"
                ls -la $(Pipeline.Workspace)/data/
              else
                echo "##[warning]No existing database - first run"
                mkdir -p $(Pipeline.Workspace)/data
              fi
            displayName: 'Check Database Status'

          # Run the extension task
          - task: ExtractPullRequests@1
            displayName: 'Extract PR Metrics'
            inputs:
              organization: 'oddessentials'
              projects: |
                marketing
                engineering
                hospitality
              pat: '$(PAT_SECRET)'
              database: '$(Pipeline.Workspace)/data/ado-insights.sqlite'
              outputDir: '$(Pipeline.Workspace)/csv_output'

          # Candidate DB: Always published (forensic)
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Candidate DB'
            condition: always()
            inputs:
              targetPath: '$(Pipeline.Workspace)/data'
              artifact: 'ado-insights-db-candidate-$(Build.BuildId)'

          # Golden DB: Only on success
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Golden DB'
            condition: succeeded()
            inputs:
              targetPath: '$(Pipeline.Workspace)/data'
              artifact: '$(ARTIFACT_NAME)'

          # CSV Artifacts
          - task: PublishPipelineArtifact@1
            displayName: 'Publish CSVs'
            condition: always()
            inputs:
              targetPath: '$(Pipeline.Workspace)/csv_output'
              artifact: 'csv-output'

          # Run Artifacts (if extension creates them)
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Run Artifacts'
            condition: always()
            continueOnError: true
            inputs:
              targetPath: '$(Pipeline.Workspace)/run_artifacts'
              artifact: 'run-artifacts'
