# Extension Verification Test Pipeline
# Purpose: Test the ADO extension task (not just CLI)
# Uses: ExtractPullRequests@1 task from the installed extension
# Cross-platform: Uses pwsh (PowerShell Core) which works on Windows, Linux, Mac

trigger: none  # Manual only

pool:
  name: 'Default'  # Self-hosted agent

variables:
  - group: ado-insights-secrets  # Contains PAT_SECRET
  - name: ARTIFACT_NAME
    value: 'ado-insights-db-ext-test'

stages:
  - stage: Extract
    displayName: 'Extract via Extension'
    jobs:
      - job: ExtractPRs
        displayName: 'Run Extension Task'
        steps:
          # Step 1: Create all directories upfront (cross-platform)
          - pwsh: |
              $dataDir = "$(Pipeline.Workspace)/data"
              $csvDir = "$(Pipeline.Workspace)/csv_output"
              $artifactsDir = "$(Pipeline.Workspace)/run_artifacts"

              New-Item -ItemType Directory -Force -Path $dataDir | Out-Null
              New-Item -ItemType Directory -Force -Path $csvDir | Out-Null
              New-Item -ItemType Directory -Force -Path $artifactsDir | Out-Null

              Write-Host "##[section]Directories created successfully"
            displayName: 'Create Directories'

          # Step 2: Try to download previous database (will fail on first run - that's OK)
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Previous Database (if exists)'
            continueOnError: true
            inputs:
              buildType: 'current'
              artifactName: '$(ARTIFACT_NAME)'
              targetPath: '$(Pipeline.Workspace)/data'

          # Step 3: Check if database exists
          - pwsh: |
              $dbPath = "$(Pipeline.Workspace)/data/ado-insights.sqlite"
              if (Test-Path $dbPath) {
                Write-Host "##[section]Found existing database - incremental run"
                Get-ChildItem "$(Pipeline.Workspace)/data"
              } else {
                Write-Host "##[warning]No existing database - first run (this is expected)"
              }
            displayName: 'Check Database Status'

          # Step 4: Run the extension task
          - task: ExtractPullRequests@1
            displayName: 'Extract PR Metrics'
            inputs:
              organization: 'oddessentials'
              projects: |
                marketing
                engineering
                hospitality
              pat: '$(PAT_SECRET)'
              database: '$(Pipeline.Workspace)/data/ado-insights.sqlite'
              outputDir: '$(Pipeline.Workspace)/csv_output'

          # Step 5: Publish artifacts
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Golden DB'
            condition: succeeded()
            inputs:
              targetPath: '$(Pipeline.Workspace)/data'
              artifact: '$(ARTIFACT_NAME)'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Candidate DB (forensic)'
            condition: always()
            inputs:
              targetPath: '$(Pipeline.Workspace)/data'
              artifact: 'ado-insights-db-candidate-$(Build.BuildId)'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish CSVs'
            condition: always()
            inputs:
              targetPath: '$(Pipeline.Workspace)/csv_output'
              artifact: 'csv-output'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Run Artifacts'
            condition: always()
            continueOnError: true
            inputs:
              targetPath: '$(Pipeline.Workspace)/run_artifacts'
              artifact: 'run-artifacts'
